// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_content_cleaning`, `blocks_to_layout_items`, `build_cleaner_from_options`, `build_epub_cleaner_from_options`, `ensure_epub_cleaned_cache`, `get_preload_executor`, `get_preprocessor_for_rules`, `locate_page_for_offset`, `locate_structured_page`, `map_align`, `map_run`, `new`, `page_has_text`, `parse_txt_file_inner`, `process_and_layout_chapter`, `process_structured_chapter`, `slice_utf8_safe`, `structured_layout_config`, `trigger_preload_async`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FfiLoadingProgress`, `StructuredPageKey`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `hash`

/// Load font from file path
Future<void> loadFontFile({required String fontName, required String fontPath}) =>
    RustLib.instance.api.crateApiLoadFontFile(fontName: fontName, fontPath: fontPath);

/// Load font from byte array
Future<void> loadFontData({required String fontName, required List<int> fontData}) =>
    RustLib.instance.api.crateApiLoadFontData(fontName: fontName, fontData: fontData);

/// Get loaded font count
Future<BigInt> getFontCount() => RustLib.instance.api.crateApiGetFontCount();

/// Parse TXT file and return book ID
Future<String> parseTxtFile({required String filePath, String? bookName}) =>
    RustLib.instance.api.crateApiParseTxtFile(filePath: filePath, bookName: bookName);

/// Parse TXT file asynchronously（在 tokio 工作线程执行，不阻塞 UI）
///
/// 大文件解析耗时随体积线性增长，同步版本会阻塞 Dart isolate；
/// 此版本通过 spawn_blocking 把解析移到线程池。
///
/// `cleaning_options` 非空时在导入阶段启用结构净化
/// （去 HTML/去广告/空白规整/智能分段），并在此文本上完成 JS 章节识别。
Future<String> parseTxtFileAsync({
  required String filePath,
  String? bookName,
  ContentCleaningOptions? cleaningOptions,
}) => RustLib.instance.api.crateApiParseTxtFileAsync(
  filePath: filePath,
  bookName: bookName,
  cleaningOptions: cleaningOptions,
);

/// 设置全局内容净化选项
Future<void> setContentCleaningOptions({required ContentCleaningOptions options}) =>
    RustLib.instance.api.crateApiSetContentCleaningOptions(options: options);

/// 清除内容净化选项（恢复默认：不净化）
Future<void> clearContentCleaningOptions() => RustLib.instance.api.crateApiClearContentCleaningOptions();

/// 运行中更新已打开书籍的净化设置（即时生效）
///
/// 更新 parser 的净化器并清空该书分页缓存；
/// 净化缓存由读取路径按 config_hash 检测变更后自动重建。
Future<void> updateBookCleaning({required String bookId, required ContentCleaningOptions options}) =>
    RustLib.instance.api.crateApiUpdateBookCleaning(bookId: bookId, options: options);

/// 解析 TXT 文件（带内容净化选项）
Future<String> parseTxtFileWithCleaning({
  required String filePath,
  String? bookName,
  required ContentCleaningOptions options,
}) => RustLib.instance.api.crateApiParseTxtFileWithCleaning(filePath: filePath, bookName: bookName, options: options);

/// 诊断用：直接从 EPUB 文件提取某章结构化内容 IR v2（JSON 字符串）
///
/// 无状态探针——不经 BOOKS 句柄（句柄版结构化阅读路径见
/// get_page_structured 等）。
/// 返回 StructuredContent 的 JSON
/// （schema 见 book_parser::content_ir，含 background/blocks）。
Future<String> epubChapterStructured({required String filePath, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiEpubChapterStructured(filePath: filePath, chapterIndex: chapterIndex);

/// Get book title
Future<String> getBookTitle({required String bookId}) => RustLib.instance.api.crateApiGetBookTitle(bookId: bookId);

/// Get chapter list
Future<List<ChapterInfo>> getChapters({required String bookId}) =>
    RustLib.instance.api.crateApiGetChapters(bookId: bookId);

/// Get chapter content
Future<String> getChapterContent({required String bookId, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiGetChapterContent(bookId: bookId, chapterIndex: chapterIndex);

/// Get chapter content with preprocessing (简繁转换、去重标题等)
Future<String> getChapterContentProcessed({
  required String bookId,
  required BigInt chapterIndex,
  required bool removeDuplicateTitle,
  required bool reSegment,
  required int chineseConvert,
}) => RustLib.instance.api.crateApiGetChapterContentProcessed(
  bookId: bookId,
  chapterIndex: chapterIndex,
  removeDuplicateTitle: removeDuplicateTitle,
  reSegment: reSegment,
  chineseConvert: chineseConvert,
);

/// Layout chapter text into pages (using new layout engine)
Future<List<PageInfo>> layoutChapter({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
}) => RustLib.instance.api.crateApiLayoutChapter(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
);

/// Get specific page (using new layout engine)
Future<PageInfo> getPage({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
}) => RustLib.instance.api.crateApiGetPage(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
);

/// Get page count for a chapter (using new layout engine)
Future<BigInt> getPageCount({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
}) => RustLib.instance.api.crateApiGetPageCount(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
);

/// Get specific page with content preprocessing (带内容预处理的分页获取)
///
/// `replace_rules`: 用户自定义替换规则（随设置传入，即时生效）
/// `anchor_char_offset`: 进度锚点——章内字符偏移；提供时返回包含该偏移的页
/// （用于设置变更后停留在原阅读位置，而非固定页码）
Future<PageInfo> getPageProcessed({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required bool removeDuplicateTitle,
  required bool reSegment,
  required int chineseConvert,
  required List<FfiReplaceRule> replaceRules,
  BigInt? anchorCharOffset,
}) => RustLib.instance.api.crateApiGetPageProcessed(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  removeDuplicateTitle: removeDuplicateTitle,
  reSegment: reSegment,
  chineseConvert: chineseConvert,
  replaceRules: replaceRules,
  anchorCharOffset: anchorCharOffset,
);

/// Get page count with content preprocessing (带内容预处理的分页计数)
Future<BigInt> getPageCountProcessed({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required bool removeDuplicateTitle,
  required bool reSegment,
  required int chineseConvert,
  required List<FfiReplaceRule> replaceRules,
}) => RustLib.instance.api.crateApiGetPageCountProcessed(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  removeDuplicateTitle: removeDuplicateTitle,
  reSegment: reSegment,
  chineseConvert: chineseConvert,
  replaceRules: replaceRules,
);

/// 结构化分页获取（EPUB 主路径）
///
/// `anchor_char_offset`: 进度锚点——章内文本字符偏移（与 TXT 路径同语义，
/// 图片项不消耗锚点）；提供时返回包含该偏移的页（跳过纯图装饰页）。
Future<PageInfo> getPageStructured({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  BigInt? anchorCharOffset,
}) => RustLib.instance.api.crateApiGetPageStructured(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  anchorCharOffset: anchorCharOffset,
);

/// 结构化分页计数（EPUB 主路径）
Future<BigInt> getPageCountStructured({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
}) => RustLib.instance.api.crateApiGetPageCountStructured(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
);

/// 读取书内资源字节（EPUB 图片；ZIP 全路径，与 IR resource_href 同基准）
Future<Uint8List> getBookResource({required String bookId, required String resourceHref}) =>
    RustLib.instance.api.crateApiGetBookResource(bookId: bookId, resourceHref: resourceHref);

/// 读取书封面字节（导入时提取；空返回=无封面）
Future<Uint8List> getBookCover({required String bookId}) => RustLib.instance.api.crateApiGetBookCover(bookId: bookId);

/// 书籍格式标记（Dart 据此分流结构化/旧 API："epub" | "txt"）
Future<String> getBookFormat({required String bookId}) => RustLib.instance.api.crateApiGetBookFormat(bookId: bookId);

/// Get glyph cache statistics
Future<String> getCacheStats() => RustLib.instance.api.crateApiGetCacheStats();

/// Release book from memory
Future<void> releaseBook({required String bookId}) => RustLib.instance.api.crateApiReleaseBook(bookId: bookId);

/// Load book source from JSON string
/// Returns book source URL as identifier
Future<String> loadBookSource({required String sourceJson}) =>
    RustLib.instance.api.crateApiLoadBookSource(sourceJson: sourceJson);

/// Load book source from FfiBookSource
Future<String> loadBookSourceFfi({required FfiBookSource source}) =>
    RustLib.instance.api.crateApiLoadBookSourceFfi(source: source);

/// Get book source as JSON string
Future<String> getBookSourceJson({required String sourceUrl}) =>
    RustLib.instance.api.crateApiGetBookSourceJson(sourceUrl: sourceUrl);

/// Search books using a book source
/// Returns JSON array of search results
Future<String> searchBook({required FfiBookSource source, required String keyword}) =>
    RustLib.instance.api.crateApiSearchBook(source: source, keyword: keyword);

/// Search books using source JSON string
Future<String> searchBookByJson({required String sourceJson, required String keyword}) =>
    RustLib.instance.api.crateApiSearchBookByJson(sourceJson: sourceJson, keyword: keyword);

/// Get book info from a book source
/// Returns JSON string of book info
Future<String> getBookInfo({required FfiBookSource source, required String bookUrl}) =>
    RustLib.instance.api.crateApiGetBookInfo(source: source, bookUrl: bookUrl);

/// Get book info using source JSON string
Future<String> getBookInfoByJson({required String sourceJson, required String bookUrl}) =>
    RustLib.instance.api.crateApiGetBookInfoByJson(sourceJson: sourceJson, bookUrl: bookUrl);

/// Get table of contents (chapter list) from a book source
/// Returns JSON array of chapters
Future<String> getToc({required FfiBookSource source, required String tocUrl}) =>
    RustLib.instance.api.crateApiGetToc(source: source, tocUrl: tocUrl);

/// Get table of contents using source JSON string
Future<String> getTocByJson({required String sourceJson, required String tocUrl}) =>
    RustLib.instance.api.crateApiGetTocByJson(sourceJson: sourceJson, tocUrl: tocUrl);

/// Get chapter content from a book source
/// Returns JSON string of chapter content
Future<String> getChapterContentFromSource({required FfiBookSource source, required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentFromSource(source: source, chapterUrl: chapterUrl);

/// Get chapter content using source JSON string
Future<String> getChapterContentFromSourceJson({required String sourceJson, required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentFromSourceJson(sourceJson: sourceJson, chapterUrl: chapterUrl);

/// List all loaded book sources (placeholder)
Future<String> listBookSources() => RustLib.instance.api.crateApiListBookSources();

/// Delete a book source
Future<void> deleteBookSource({required String sourceUrl}) =>
    RustLib.instance.api.crateApiDeleteBookSource(sourceUrl: sourceUrl);

/// Enable/disable a book source
Future<void> setBookSourceEnabled({required String sourceUrl, required bool enabled}) =>
    RustLib.instance.api.crateApiSetBookSourceEnabled(sourceUrl: sourceUrl, enabled: enabled);

/// Get specific page with caching (优化版，使用分页缓存)
Future<PageInfo> getPageCached({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
}) => RustLib.instance.api.crateApiGetPageCached(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
);

/// Get page count with caching (优化版，使用分页缓存)
Future<BigInt> getPageCountCached({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
}) => RustLib.instance.api.crateApiGetPageCountCached(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
);

/// Get specific page with caching and preprocessing (最优化版本)
Future<PageInfo> getPageCachedProcessed({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required bool removeDuplicateTitle,
  required bool reSegment,
  required int chineseConvert,
}) => RustLib.instance.api.crateApiGetPageCachedProcessed(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  removeDuplicateTitle: removeDuplicateTitle,
  reSegment: reSegment,
  chineseConvert: chineseConvert,
);

/// 获取分页缓存统计信息（用于性能调试）
Future<String> getPaginationCacheStats() => RustLib.instance.api.crateApiGetPaginationCacheStats();

/// 清除指定书籍的分页缓存
Future<void> clearPaginationCacheForBook({required String bookId}) =>
    RustLib.instance.api.crateApiClearPaginationCacheForBook(bookId: bookId);

/// 清除所有分页缓存
Future<void> clearAllPaginationCache() => RustLib.instance.api.crateApiClearAllPaginationCache();

/// 检测文件格式
///
/// 返回格式名称："txt", "epub", "unknown"
Future<String> detectBookFormat({required String filePath}) =>
    RustLib.instance.api.crateApiDetectBookFormat(filePath: filePath);

/// 获取书籍信息
Future<FfiBookMetadata> getBookInfoById({required String bookId}) =>
    RustLib.instance.api.crateApiGetBookInfoById(bookId: bookId);

/// 检测文件格式并返回详细信息
Future<FfiFormatInfo> detectFormatDetailed({required String filePath}) =>
    RustLib.instance.api.crateApiDetectFormatDetailed(filePath: filePath);

/// 创建阅读会话
Future<String> createReadingSession({
  required String filePath,
  required double width,
  required double height,
  required double fontSize,
  required String fontName,
}) => RustLib.instance.api.crateApiCreateReadingSession(
  filePath: filePath,
  width: width,
  height: height,
  fontSize: fontSize,
  fontName: fontName,
);

/// 获取会话的书籍信息
Future<FfiBookMetadata> getSessionBookInfo({required String sessionId}) =>
    RustLib.instance.api.crateApiGetSessionBookInfo(sessionId: sessionId);

/// 获取会话的章节列表
Future<List<ChapterInfo>> getSessionChapters({required String sessionId}) =>
    RustLib.instance.api.crateApiGetSessionChapters(sessionId: sessionId);

/// 获取会话的指定章节内容
Future<String> getSessionChapterContent({required String sessionId, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiGetSessionChapterContent(sessionId: sessionId, chapterIndex: chapterIndex);

/// 关闭阅读会话
Future<void> closeSession({required String sessionId}) =>
    RustLib.instance.api.crateApiCloseSession(sessionId: sessionId);

/// 获取活跃会话数量
Future<BigInt> getActiveSessionCount() => RustLib.instance.api.crateApiGetActiveSessionCount();

/// 获取预加载统计信息
Future<FfiPreloadStats> getPreloadStats() => RustLib.instance.api.crateApiGetPreloadStats();

/// 使用增强的预处理管道处理章节内容
Future<String> processChapterContent({
  required String bookId,
  required BigInt chapterIndex,
  FfiProcessOptions? config,
}) => RustLib.instance.api.crateApiProcessChapterContent(bookId: bookId, chapterIndex: chapterIndex, config: config);

/// 批量处理多个章节（异步）
Future<List<String>> batchProcessChapters({
  required String bookId,
  required Uint64List chapterIndices,
  required FfiProcessOptions options,
}) =>
    RustLib.instance.api.crateApiBatchProcessChapters(bookId: bookId, chapterIndices: chapterIndices, options: options);

/// 清除指定书籍的分页缓存
Future<void> clearBookCache({required String bookId}) => RustLib.instance.api.crateApiClearBookCache(bookId: bookId);

/// 清除所有缓存
Future<void> clearAllCaches() => RustLib.instance.api.crateApiClearAllCaches();

/// 获取缓存统计信息
Future<FfiCacheStats> getCacheStatistics() => RustLib.instance.api.crateApiGetCacheStatistics();

/// 诊断文件编码
Future<String> diagnoseFileEncodingApi({required String filePath}) =>
    RustLib.instance.api.crateApiDiagnoseFileEncodingApi(filePath: filePath);

/// 诊断章节内容编码
Future<String> diagnoseChapterEncodingApi({required String bookId, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiDiagnoseChapterEncodingApi(bookId: bookId, chapterIndex: chapterIndex);

/// 对比原始内容和处理后内容
Future<String> compareRawAndProcessedContent({required String bookId, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiCompareRawAndProcessedContent(bookId: bookId, chapterIndex: chapterIndex);

/// 手动触发单章预加载
Future<void> preloadChapter({required String bookId, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiPreloadChapter(bookId: bookId, chapterIndex: chapterIndex);

/// 获取预加载队列深度
Future<BigInt> getPreloadQueueDepth() => RustLib.instance.api.crateApiGetPreloadQueueDepth();

/// 取消书籍的所有预加载任务
/// 注意: 当前 PreloadExecutor 不支持按 book_id 取消
/// 此函数为占位实现，完整功能需要在 UnifiedScheduler 中实现
Future<void> cancelPreload({required String bookId}) => RustLib.instance.api.crateApiCancelPreload(bookId: bookId);

/// 内容净化选项
class ContentCleaningOptions {
  /// 繁简转换模式: "none", "t2s"(繁转简), "s2t"(简转繁)
  final String convertMode;

  /// 段落处理模式: "none", "smart"(智能), "force"(强制)
  final String paragraphMode;

  /// 是否清理 HTML 标签
  final bool cleanHtml;

  /// 是否删除广告
  final bool removeAds;

  const ContentCleaningOptions({
    required this.convertMode,
    required this.paragraphMode,
    required this.cleanHtml,
    required this.removeAds,
  });

  static Future<ContentCleaningOptions> default_() => RustLib.instance.api.crateApiContentCleaningOptionsDefault();

  @override
  int get hashCode => convertMode.hashCode ^ paragraphMode.hashCode ^ cleanHtml.hashCode ^ removeAds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentCleaningOptions &&
          runtimeType == other.runtimeType &&
          convertMode == other.convertMode &&
          paragraphMode == other.paragraphMode &&
          cleanHtml == other.cleanHtml &&
          removeAds == other.removeAds;
}

/// FFI 书籍元信息
class FfiBookMetadata {
  /// 书籍 ID
  final String bookId;

  /// 书名
  final String title;

  /// 作者
  final String author;

  /// 总章节数
  final BigInt totalChapters;

  /// 文件格式
  final String format;

  const FfiBookMetadata({
    required this.bookId,
    required this.title,
    required this.author,
    required this.totalChapters,
    required this.format,
  });

  @override
  int get hashCode => bookId.hashCode ^ title.hashCode ^ author.hashCode ^ totalChapters.hashCode ^ format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiBookMetadata &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          author == other.author &&
          totalChapters == other.totalChapters &&
          format == other.format;
}

/// FFI 缓存统计信息
class FfiCacheStats {
  final BigInt hits;
  final BigInt misses;
  final BigInt size;
  final BigInt capacity;

  const FfiCacheStats({required this.hits, required this.misses, required this.size, required this.capacity});

  @override
  int get hashCode => hits.hashCode ^ misses.hashCode ^ size.hashCode ^ capacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCacheStats &&
          runtimeType == other.runtimeType &&
          hits == other.hits &&
          misses == other.misses &&
          size == other.size &&
          capacity == other.capacity;
}

/// FFI 格式检测结果
class FfiFormatInfo {
  final String format;
  final String formatName;
  final String method;
  final double confidence;

  const FfiFormatInfo({required this.format, required this.formatName, required this.method, required this.confidence});

  @override
  int get hashCode => format.hashCode ^ formatName.hashCode ^ method.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFormatInfo &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          formatName == other.formatName &&
          method == other.method &&
          confidence == other.confidence;
}

/// FFI 预加载统计信息
class FfiPreloadStats {
  final BigInt totalTasks;
  final BigInt completedTasks;
  final BigInt failedTasks;
  final BigInt cancelledTasks;

  const FfiPreloadStats({
    required this.totalTasks,
    required this.completedTasks,
    required this.failedTasks,
    required this.cancelledTasks,
  });

  @override
  int get hashCode => totalTasks.hashCode ^ completedTasks.hashCode ^ failedTasks.hashCode ^ cancelledTasks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPreloadStats &&
          runtimeType == other.runtimeType &&
          totalTasks == other.totalTasks &&
          completedTasks == other.completedTasks &&
          failedTasks == other.failedTasks &&
          cancelledTasks == other.cancelledTasks;
}

/// FFI 处理选项
class FfiProcessOptions {
  final bool removeDuplicateTitle;
  final bool reSegment;
  final int chineseConvert;
  final bool adaptSpecialStyle;

  const FfiProcessOptions({
    required this.removeDuplicateTitle,
    required this.reSegment,
    required this.chineseConvert,
    required this.adaptSpecialStyle,
  });

  static Future<FfiProcessOptions> default_() => RustLib.instance.api.crateApiFfiProcessOptionsDefault();

  @override
  int get hashCode =>
      removeDuplicateTitle.hashCode ^ reSegment.hashCode ^ chineseConvert.hashCode ^ adaptSpecialStyle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiProcessOptions &&
          runtimeType == other.runtimeType &&
          removeDuplicateTitle == other.removeDuplicateTitle &&
          reSegment == other.reSegment &&
          chineseConvert == other.chineseConvert &&
          adaptSpecialStyle == other.adaptSpecialStyle;
}

/// FFI 替换规则（用户自定义净化/替换规则）
///
/// `rule_type`: 0=字符串直替, 1=正则, 2=JS 脚本（pattern 承载脚本，
/// 以全局 `chapterContent` 为输入、返回替换后全文，legado 风格）
class FfiReplaceRule {
  final String pattern;
  final String replacement;
  final int ruleType;
  final bool enabled;

  const FfiReplaceRule({
    required this.pattern,
    required this.replacement,
    required this.ruleType,
    required this.enabled,
  });

  @override
  int get hashCode => pattern.hashCode ^ replacement.hashCode ^ ruleType.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiReplaceRule &&
          runtimeType == other.runtimeType &&
          pattern == other.pattern &&
          replacement == other.replacement &&
          ruleType == other.ruleType &&
          enabled == other.enabled;
}
