// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_content_cleaning`, `apply_paragraph_format_settings`, `blocks_to_layout_items_inner`, `blocks_to_layout_items`, `build_cleaner_from_options`, `build_epub_cleaner_from_options`, `build_layout_engine`, `clear_structured_pagination_cache_for_book`, `clip_runs`, `effective_paragraph_spacing`, `ensure_epub_cleaned_cache`, `from_args`, `get_chapter_content_impl`, `get_chapter_content_quiet`, `get_preload_executor`, `get_preload_runtime`, `get_preprocessor_for_rules`, `invalidate_preprocessed_cache`, `locate_page_for_offset`, `locate_structured_page`, `map_align`, `map_run`, `new`, `page_has_text`, `parse_txt_file_inner`, `preload_txt_warm`, `process_and_layout_chapter_inner`, `process_and_layout_chapter`, `process_structured_chapter`, `remember_txt_layout`, `shared_tokio_runtime`, `slice_utf8_safe`, `structured_cache_key`, `structured_layout_config`, `trigger_preload_async`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FfiLoadingProgress`, `PreloadRuntime`, `StructuredPageKey`, `StructuredParams`, `TxtLayoutSnapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `hash`

/// Load font from file path（软失败：找不到文件/读失败时只 log，不抛错）
///
/// 行为：写入 `tracing` 日志 + 静默返回 Ok，让上层 Dart 代码不因字体
/// 加载失败而崩溃。FontManager 内置 Noto Sans CJK SC 默认字体，
/// 即使所有 load_font_file 失败，仍有可用字体兜底。
Future<void> loadFontFile({required String fontName, required String fontPath}) =>
    RustLib.instance.api.crateApiLoadFontFile(fontName: fontName, fontPath: fontPath);

/// Load font from byte array
Future<void> loadFontData({required String fontName, required List<int> fontData}) =>
    RustLib.instance.api.crateApiLoadFontData(fontName: fontName, fontData: fontData);

/// Get loaded font count
Future<BigInt> getFontCount() => RustLib.instance.api.crateApiGetFontCount();

/// 切换默认字体（用户选字体后调用）
///
/// name 必须是已 load_font_* 加载过的字体名，否则抛错。
/// 切换后清共享字形缓存防旧字体字形混入；同时清共享 MeasureCache
/// （旧字体的 Skia 实测宽度对当前字体失效）。
Future<void> setDefaultFont({required String fontName}) =>
    RustLib.instance.api.crateApiSetDefaultFont(fontName: fontName);

/// 获取当前默认字体名
Future<String> getDefaultFontName() => RustLib.instance.api.crateApiGetDefaultFontName();

/// M10-B：批量写入 Skia 实测宽度到 MeasureCache。
///
/// 典型调用：Dart MeasureTextService 测完本章常用子串后调一次（数百~数千条）。
/// 内部 LRU 自动淘汰，单章 ≤ 50k 条足够覆盖。重复写入覆盖（写入永远是最新值）。
Future<BigInt> feedTextWidths({required List<FfiTextWidth> widths}) =>
    RustLib.instance.api.crateApiFeedTextWidths(widths: widths);

/// M10-B：清空 MeasureCache（Dart 端主动失效时使用，例如 settings 变更或字体切换兜底）
Future<BigInt> clearMeasureCache() => RustLib.instance.api.crateApiClearMeasureCache();

/// M10-B：查询 MeasureCache 状态（诊断用：当前条目数 / 容量）
Future<String> getMeasureCacheStats() => RustLib.instance.api.crateApiGetMeasureCacheStats();

/// Parse TXT file and return book ID
Future<String> parseTxtFile({required String filePath, String? bookName}) =>
    RustLib.instance.api.crateApiParseTxtFile(filePath: filePath, bookName: bookName);

/// Parse TXT file asynchronously（在 tokio 工作线程执行，不阻塞 UI）
///
/// 大文件解析耗时随体积线性增长，同步版本会阻塞 Dart isolate；
/// 此版本通过 spawn_blocking 把解析移到线程池。
///
/// `cleaning_options` 非空时在导入阶段启用结构净化
/// （去 HTML/去广告/空白规整/智能分段），并在此文本上完成 JS 章节识别。
Future<String> parseTxtFileAsync({
  required String filePath,
  String? bookName,
  ContentCleaningOptions? cleaningOptions,
}) => RustLib.instance.api.crateApiParseTxtFileAsync(
  filePath: filePath,
  bookName: bookName,
  cleaningOptions: cleaningOptions,
);

/// 设置全局内容净化选项
Future<void> setContentCleaningOptions({required ContentCleaningOptions options}) =>
    RustLib.instance.api.crateApiSetContentCleaningOptions(options: options);

/// 清除内容净化选项（恢复默认：不净化）
Future<void> clearContentCleaningOptions() => RustLib.instance.api.crateApiClearContentCleaningOptions();

/// M9：设置全局段落格式化参数
///
/// Dart 侧调用：用户在设置 UI 修改缩进/重分段模式/切分阈值时，
/// 通过此函数同步 Rust 全局设置，随后 FFI 分页调用自动应用。
/// 阈值钳制在 [20, 2000]，防病态输入（过小退化为逐句切分、过大等同不切）。
Future<void> setParagraphFormatSettings({
  required bool enableIndent,
  required int indentSizeChars,
  required double paragraphSpacingMultiplier,
  required int reParagraphMode,
  required int smartSplitThreshold,
  required int aggressiveSplitThreshold,
}) => RustLib.instance.api.crateApiSetParagraphFormatSettings(
  enableIndent: enableIndent,
  indentSizeChars: indentSizeChars,
  paragraphSpacingMultiplier: paragraphSpacingMultiplier,
  reParagraphMode: reParagraphMode,
  smartSplitThreshold: smartSplitThreshold,
  aggressiveSplitThreshold: aggressiveSplitThreshold,
);

/// 运行中更新已打开书籍的净化设置（即时生效）
///
/// 更新 parser 的净化器并清空该书分页缓存；
/// 净化缓存由读取路径按 config_hash 检测变更后自动重建。
Future<void> updateBookCleaning({required String bookId, required ContentCleaningOptions options}) =>
    RustLib.instance.api.crateApiUpdateBookCleaning(bookId: bookId, options: options);

/// 解析 TXT 文件（带内容净化选项）
Future<String> parseTxtFileWithCleaning({
  required String filePath,
  String? bookName,
  required ContentCleaningOptions options,
}) => RustLib.instance.api.crateApiParseTxtFileWithCleaning(filePath: filePath, bookName: bookName, options: options);

/// 诊断用：直接从 EPUB 文件提取某章结构化内容 IR v2（JSON 字符串）
///
/// 无状态探针——不经 BOOKS 句柄（句柄版结构化阅读路径见
/// get_page_structured 等）。
/// 返回 StructuredContent 的 JSON
/// （schema 见 book_parser::content_ir，含 background/blocks）。
Future<String> epubChapterStructured({required String filePath, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiEpubChapterStructured(filePath: filePath, chapterIndex: chapterIndex);

/// Get book title
Future<String> getBookTitle({required String bookId}) => RustLib.instance.api.crateApiGetBookTitle(bookId: bookId);

/// Get chapter list
Future<List<ChapterInfo>> getChapters({required String bookId}) =>
    RustLib.instance.api.crateApiGetChapters(bookId: bookId);

/// Get chapter content
Future<String> getChapterContent({required String bookId, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiGetChapterContent(bookId: bookId, chapterIndex: chapterIndex);

/// Get chapter content with preprocessing (简繁转换、去重标题等)
Future<String> getChapterContentProcessed({
  required String bookId,
  required BigInt chapterIndex,
  required bool removeDuplicateTitle,
  required bool reSegment,
  required int chineseConvert,
}) => RustLib.instance.api.crateApiGetChapterContentProcessed(
  bookId: bookId,
  chapterIndex: chapterIndex,
  removeDuplicateTitle: removeDuplicateTitle,
  reSegment: reSegment,
  chineseConvert: chineseConvert,
);

/// Layout chapter text into pages (using new layout engine)
Future<List<PageInfo>> layoutChapter({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
}) => RustLib.instance.api.crateApiLayoutChapter(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
);

/// Get specific page (using new layout engine)
Future<PageInfo> getPage({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required double pageFillThreshold,
}) => RustLib.instance.api.crateApiGetPage(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  pageFillThreshold: pageFillThreshold,
);

/// Get page count for a chapter (using new layout engine)
Future<BigInt> getPageCount({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required double pageFillThreshold,
}) => RustLib.instance.api.crateApiGetPageCount(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  pageFillThreshold: pageFillThreshold,
);

/// Get specific page with content preprocessing (带内容预处理的分页获取)
///
/// `replace_rules`: 用户自定义替换规则（随设置传入，即时生效）
/// `anchor_char_offset`: 进度锚点——章内字符偏移；提供时返回包含该偏移的页
/// （用于设置变更后停留在原阅读位置，而非固定页码）
Future<PageInfo> getPageProcessed({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required bool removeDuplicateTitle,
  required bool reSegment,
  required int chineseConvert,
  required List<FfiReplaceRule> replaceRules,
  BigInt? anchorCharOffset,
  required double pageFillThreshold,
  required BigInt paraFormatHash,
}) => RustLib.instance.api.crateApiGetPageProcessed(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  removeDuplicateTitle: removeDuplicateTitle,
  reSegment: reSegment,
  chineseConvert: chineseConvert,
  replaceRules: replaceRules,
  anchorCharOffset: anchorCharOffset,
  pageFillThreshold: pageFillThreshold,
  paraFormatHash: paraFormatHash,
);

/// Get page count with content preprocessing (带内容预处理的分页计数)
Future<BigInt> getPageCountProcessed({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required bool removeDuplicateTitle,
  required bool reSegment,
  required int chineseConvert,
  required List<FfiReplaceRule> replaceRules,
  required double pageFillThreshold,
  required BigInt paraFormatHash,
}) => RustLib.instance.api.crateApiGetPageCountProcessed(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  removeDuplicateTitle: removeDuplicateTitle,
  reSegment: reSegment,
  chineseConvert: chineseConvert,
  replaceRules: replaceRules,
  pageFillThreshold: pageFillThreshold,
  paraFormatHash: paraFormatHash,
);

/// 结构化分页获取（EPUB 主路径）
///
/// `anchor_char_offset`: 进度锚点——章内文本字符偏移（与 TXT 路径同语义，
/// 图片项不消耗锚点）；提供时返回包含该偏移的页（跳过纯图装饰页）。
/// `chinese_convert`: 阅读级简繁转换（0=无 1=简→繁 2=繁→简；与 TXT 同编码）
Future<PageInfo> getPageStructured({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  BigInt? anchorCharOffset,
  required int chineseConvert,
  required double pageFillThreshold,
  required bool showComments,
  required BigInt paraFormatHash,
}) => RustLib.instance.api.crateApiGetPageStructured(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  anchorCharOffset: anchorCharOffset,
  chineseConvert: chineseConvert,
  pageFillThreshold: pageFillThreshold,
  showComments: showComments,
  paraFormatHash: paraFormatHash,
);

/// 结构化分页计数（EPUB 主路径）
Future<BigInt> getPageCountStructured({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required int chineseConvert,
  required double pageFillThreshold,
  required bool showComments,
  required BigInt paraFormatHash,
}) => RustLib.instance.api.crateApiGetPageCountStructured(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  chineseConvert: chineseConvert,
  pageFillThreshold: pageFillThreshold,
  showComments: showComments,
  paraFormatHash: paraFormatHash,
);

/// EPUB 翻章预取：以与前台完全一致的参数预计算目标章分页并写入缓存。
///
/// 幂等——键已存在立即返回 true；BOOKS 写锁被前台占用时让路返回 false。
/// ⚠ 参数必须与 get_page_structured/get_page_count_structured 完全同参
/// （f32 按 bits 入键），否则入键错位、预取无效。Dart 侧 fire-and-forget
/// 调用（当前章渲染完成后预取下一章）。
Future<bool> prefetchStructuredChapter({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required int chineseConvert,
  required double pageFillThreshold,
  required bool showComments,
  required BigInt paraFormatHash,
}) => RustLib.instance.api.crateApiPrefetchStructuredChapter(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  chineseConvert: chineseConvert,
  pageFillThreshold: pageFillThreshold,
  showComments: showComments,
  paraFormatHash: paraFormatHash,
);

/// 读取书内资源字节（EPUB 图片；ZIP 全路径，与 IR resource_href 同基准）
///
/// 快路径：read 锁内窥探 parser 资源缓存，命中（渲染重复图/预热去重后
/// 的图）直接返回，不与前台分页（BOOKS.write）争写锁；未命中才落写锁
/// 慢路径（ZIP 读取 + 写缓存，仅每资源首次）。
Future<Uint8List> getBookResource({required String bookId, required String resourceHref}) =>
    RustLib.instance.api.crateApiGetBookResource(bookId: bookId, resourceHref: resourceHref);

/// 读取书封面字节（导入时提取；空返回=无封面）
Future<Uint8List> getBookCover({required String bookId}) => RustLib.instance.api.crateApiGetBookCover(bookId: bookId);

/// 书籍格式标记（Dart 据此分流结构化/旧 API："epub" | "txt"）
Future<String> getBookFormat({required String bookId}) => RustLib.instance.api.crateApiGetBookFormat(bookId: bookId);

/// Get glyph cache statistics
Future<String> getCacheStats() => RustLib.instance.api.crateApiGetCacheStats();

/// Release book from memory
Future<void> releaseBook({required String bookId}) => RustLib.instance.api.crateApiReleaseBook(bookId: bookId);

/// Load book source from JSON string
/// Returns book source URL as identifier
Future<String> loadBookSource({required String sourceJson}) =>
    RustLib.instance.api.crateApiLoadBookSource(sourceJson: sourceJson);

/// Load book source from FfiBookSource
Future<String> loadBookSourceFfi({required FfiBookSource source}) =>
    RustLib.instance.api.crateApiLoadBookSourceFfi(source: source);

/// Get book source as JSON string
Future<String> getBookSourceJson({required String sourceUrl}) =>
    RustLib.instance.api.crateApiGetBookSourceJson(sourceUrl: sourceUrl);

/// Search books using a book source
/// Returns JSON array of search results
Future<String> searchBook({required FfiBookSource source, required String keyword}) =>
    RustLib.instance.api.crateApiSearchBook(source: source, keyword: keyword);

/// Search books using source JSON string
Future<String> searchBookByJson({required String sourceJson, required String keyword}) =>
    RustLib.instance.api.crateApiSearchBookByJson(sourceJson: sourceJson, keyword: keyword);

/// Get book info from a book source
/// Returns JSON string of book info
Future<String> getBookInfo({required FfiBookSource source, required String bookUrl}) =>
    RustLib.instance.api.crateApiGetBookInfo(source: source, bookUrl: bookUrl);

/// Get book info using source JSON string
Future<String> getBookInfoByJson({required String sourceJson, required String bookUrl}) =>
    RustLib.instance.api.crateApiGetBookInfoByJson(sourceJson: sourceJson, bookUrl: bookUrl);

/// Get table of contents (chapter list) from a book source
/// Returns JSON array of chapters
Future<String> getToc({required FfiBookSource source, required String tocUrl}) =>
    RustLib.instance.api.crateApiGetToc(source: source, tocUrl: tocUrl);

/// Get table of contents using source JSON string
Future<String> getTocByJson({required String sourceJson, required String tocUrl}) =>
    RustLib.instance.api.crateApiGetTocByJson(sourceJson: sourceJson, tocUrl: tocUrl);

/// Get chapter content from a book source
/// Returns JSON string of chapter content
Future<String> getChapterContentFromSource({required FfiBookSource source, required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentFromSource(source: source, chapterUrl: chapterUrl);

/// Get chapter content using source JSON string
Future<String> getChapterContentFromSourceJson({required String sourceJson, required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentFromSourceJson(sourceJson: sourceJson, chapterUrl: chapterUrl);

/// List all loaded book sources (placeholder)
Future<String> listBookSources() => RustLib.instance.api.crateApiListBookSources();

/// Delete a book source
Future<void> deleteBookSource({required String sourceUrl}) =>
    RustLib.instance.api.crateApiDeleteBookSource(sourceUrl: sourceUrl);

/// Enable/disable a book source
Future<void> setBookSourceEnabled({required String sourceUrl, required bool enabled}) =>
    RustLib.instance.api.crateApiSetBookSourceEnabled(sourceUrl: sourceUrl, enabled: enabled);

/// Get specific page with caching (优化版，使用分页缓存)
Future<PageInfo> getPageCached({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
}) => RustLib.instance.api.crateApiGetPageCached(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
);

/// Get page count with caching (优化版，使用分页缓存)
Future<BigInt> getPageCountCached({
  required String bookId,
  required BigInt chapterIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
}) => RustLib.instance.api.crateApiGetPageCountCached(
  bookId: bookId,
  chapterIndex: chapterIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
);

/// Get specific page with caching and preprocessing (最优化版本)
Future<PageInfo> getPageCachedProcessed({
  required String bookId,
  required BigInt chapterIndex,
  required BigInt pageIndex,
  required double width,
  required double height,
  required double fontSize,
  required double lineHeightMultiplier,
  required double paddingLeft,
  required double paddingTop,
  required double paddingRight,
  required double paddingBottom,
  required String fontName,
  required bool removeDuplicateTitle,
  required bool reSegment,
  required int chineseConvert,
}) => RustLib.instance.api.crateApiGetPageCachedProcessed(
  bookId: bookId,
  chapterIndex: chapterIndex,
  pageIndex: pageIndex,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeightMultiplier: lineHeightMultiplier,
  paddingLeft: paddingLeft,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  fontName: fontName,
  removeDuplicateTitle: removeDuplicateTitle,
  reSegment: reSegment,
  chineseConvert: chineseConvert,
);

/// 获取分页缓存统计信息（用于性能调试）
Future<String> getPaginationCacheStats() => RustLib.instance.api.crateApiGetPaginationCacheStats();

/// 清除指定书籍的分页缓存
Future<void> clearPaginationCacheForBook({required String bookId}) =>
    RustLib.instance.api.crateApiClearPaginationCacheForBook(bookId: bookId);

/// 清除所有分页缓存
Future<void> clearAllPaginationCache() => RustLib.instance.api.crateApiClearAllPaginationCache();

/// 检测文件格式
///
/// 返回格式名称："txt", "epub", "unknown"
Future<String> detectBookFormat({required String filePath}) =>
    RustLib.instance.api.crateApiDetectBookFormat(filePath: filePath);

/// 获取书籍信息
Future<FfiBookMetadata> getBookInfoById({required String bookId}) =>
    RustLib.instance.api.crateApiGetBookInfoById(bookId: bookId);

/// 检测文件格式并返回详细信息
Future<FfiFormatInfo> detectFormatDetailed({required String filePath}) =>
    RustLib.instance.api.crateApiDetectFormatDetailed(filePath: filePath);

/// 创建阅读会话
Future<String> createReadingSession({
  required String filePath,
  required double width,
  required double height,
  required double fontSize,
  required String fontName,
}) => RustLib.instance.api.crateApiCreateReadingSession(
  filePath: filePath,
  width: width,
  height: height,
  fontSize: fontSize,
  fontName: fontName,
);

/// 获取会话的书籍信息
Future<FfiBookMetadata> getSessionBookInfo({required String sessionId}) =>
    RustLib.instance.api.crateApiGetSessionBookInfo(sessionId: sessionId);

/// 获取会话的章节列表
Future<List<ChapterInfo>> getSessionChapters({required String sessionId}) =>
    RustLib.instance.api.crateApiGetSessionChapters(sessionId: sessionId);

/// 获取会话的指定章节内容
Future<String> getSessionChapterContent({required String sessionId, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiGetSessionChapterContent(sessionId: sessionId, chapterIndex: chapterIndex);

/// 关闭阅读会话
Future<void> closeSession({required String sessionId}) =>
    RustLib.instance.api.crateApiCloseSession(sessionId: sessionId);

/// 获取活跃会话数量
Future<BigInt> getActiveSessionCount() => RustLib.instance.api.crateApiGetActiveSessionCount();

/// 获取预加载统计信息
Future<FfiPreloadStats> getPreloadStats() => RustLib.instance.api.crateApiGetPreloadStats();

/// 使用增强的预处理管道处理章节内容
Future<String> processChapterContent({
  required String bookId,
  required BigInt chapterIndex,
  FfiProcessOptions? config,
}) => RustLib.instance.api.crateApiProcessChapterContent(bookId: bookId, chapterIndex: chapterIndex, config: config);

/// 批量处理多个章节（异步）
Future<List<String>> batchProcessChapters({
  required String bookId,
  required Uint64List chapterIndices,
  required FfiProcessOptions options,
}) =>
    RustLib.instance.api.crateApiBatchProcessChapters(bookId: bookId, chapterIndices: chapterIndices, options: options);

/// 清除指定书籍的分页缓存
Future<void> clearBookCache({required String bookId}) => RustLib.instance.api.crateApiClearBookCache(bookId: bookId);

/// 清除所有缓存
Future<void> clearAllCaches() => RustLib.instance.api.crateApiClearAllCaches();

/// 获取缓存统计信息
Future<FfiCacheStats> getCacheStatistics() => RustLib.instance.api.crateApiGetCacheStatistics();

/// 诊断文件编码
Future<String> diagnoseFileEncodingApi({required String filePath}) =>
    RustLib.instance.api.crateApiDiagnoseFileEncodingApi(filePath: filePath);

/// 诊断章节内容编码
Future<String> diagnoseChapterEncodingApi({required String bookId, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiDiagnoseChapterEncodingApi(bookId: bookId, chapterIndex: chapterIndex);

/// 对比原始内容和处理后内容
Future<String> compareRawAndProcessedContent({required String bookId, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiCompareRawAndProcessedContent(bookId: bookId, chapterIndex: chapterIndex);

/// 内容净化选项
class ContentCleaningOptions {
  /// 繁简转换模式: "none", "t2s"(繁转简), "s2t"(简转繁)
  final String convertMode;

  /// 段落处理模式: "none", "smart"(智能), "force"(强制)
  final String paragraphMode;

  /// 是否清理 HTML 标签
  final bool cleanHtml;

  /// 是否删除广告
  final bool removeAds;

  const ContentCleaningOptions({
    required this.convertMode,
    required this.paragraphMode,
    required this.cleanHtml,
    required this.removeAds,
  });

  static Future<ContentCleaningOptions> default_() => RustLib.instance.api.crateApiContentCleaningOptionsDefault();

  @override
  int get hashCode => convertMode.hashCode ^ paragraphMode.hashCode ^ cleanHtml.hashCode ^ removeAds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentCleaningOptions &&
          runtimeType == other.runtimeType &&
          convertMode == other.convertMode &&
          paragraphMode == other.paragraphMode &&
          cleanHtml == other.cleanHtml &&
          removeAds == other.removeAds;
}

/// FFI 书籍元信息
class FfiBookMetadata {
  /// 书籍 ID
  final String bookId;

  /// 书名
  final String title;

  /// 作者
  final String author;

  /// 总章节数
  final BigInt totalChapters;

  /// 文件格式
  final String format;

  const FfiBookMetadata({
    required this.bookId,
    required this.title,
    required this.author,
    required this.totalChapters,
    required this.format,
  });

  @override
  int get hashCode => bookId.hashCode ^ title.hashCode ^ author.hashCode ^ totalChapters.hashCode ^ format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiBookMetadata &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          author == other.author &&
          totalChapters == other.totalChapters &&
          format == other.format;
}

/// FFI 缓存统计信息
class FfiCacheStats {
  final BigInt hits;
  final BigInt misses;
  final BigInt size;
  final BigInt capacity;

  const FfiCacheStats({required this.hits, required this.misses, required this.size, required this.capacity});

  @override
  int get hashCode => hits.hashCode ^ misses.hashCode ^ size.hashCode ^ capacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCacheStats &&
          runtimeType == other.runtimeType &&
          hits == other.hits &&
          misses == other.misses &&
          size == other.size &&
          capacity == other.capacity;
}

/// FFI 格式检测结果
class FfiFormatInfo {
  final String format;
  final String formatName;
  final String method;
  final double confidence;

  const FfiFormatInfo({required this.format, required this.formatName, required this.method, required this.confidence});

  @override
  int get hashCode => format.hashCode ^ formatName.hashCode ^ method.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFormatInfo &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          formatName == other.formatName &&
          method == other.method &&
          confidence == other.confidence;
}

/// FFI 预加载统计信息
class FfiPreloadStats {
  final BigInt totalTasks;
  final BigInt completedTasks;
  final BigInt failedTasks;
  final BigInt cancelledTasks;

  const FfiPreloadStats({
    required this.totalTasks,
    required this.completedTasks,
    required this.failedTasks,
    required this.cancelledTasks,
  });

  @override
  int get hashCode => totalTasks.hashCode ^ completedTasks.hashCode ^ failedTasks.hashCode ^ cancelledTasks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPreloadStats &&
          runtimeType == other.runtimeType &&
          totalTasks == other.totalTasks &&
          completedTasks == other.completedTasks &&
          failedTasks == other.failedTasks &&
          cancelledTasks == other.cancelledTasks;
}

/// FFI 处理选项
class FfiProcessOptions {
  final bool removeDuplicateTitle;
  final bool reSegment;
  final int chineseConvert;
  final bool adaptSpecialStyle;

  const FfiProcessOptions({
    required this.removeDuplicateTitle,
    required this.reSegment,
    required this.chineseConvert,
    required this.adaptSpecialStyle,
  });

  static Future<FfiProcessOptions> default_() => RustLib.instance.api.crateApiFfiProcessOptionsDefault();

  @override
  int get hashCode =>
      removeDuplicateTitle.hashCode ^ reSegment.hashCode ^ chineseConvert.hashCode ^ adaptSpecialStyle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiProcessOptions &&
          runtimeType == other.runtimeType &&
          removeDuplicateTitle == other.removeDuplicateTitle &&
          reSegment == other.reSegment &&
          chineseConvert == other.chineseConvert &&
          adaptSpecialStyle == other.adaptSpecialStyle;
}

/// FFI 替换规则（用户自定义净化/替换规则）
///
/// `rule_type`: 0=字符串直替, 1=正则, 2=JS 脚本（pattern 承载脚本，
/// 以全局 `chapterContent` 为输入、返回替换后全文，legado 风格）
class FfiReplaceRule {
  final String pattern;
  final String replacement;
  final int ruleType;
  final bool enabled;

  const FfiReplaceRule({
    required this.pattern,
    required this.replacement,
    required this.ruleType,
    required this.enabled,
  });

  @override
  int get hashCode => pattern.hashCode ^ replacement.hashCode ^ ruleType.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiReplaceRule &&
          runtimeType == other.runtimeType &&
          pattern == other.pattern &&
          replacement == other.replacement &&
          ruleType == other.ruleType &&
          enabled == other.enabled;
}

/// M10-B：单条测量结果（font_name + font_size + text + width_px）
///
/// text 必须与 Rust layout 期间实际查询的子串**逐字节一致**——内部 key 用
/// SipHash(text) 而非 text 本身，避免 key 长度爆炸。
class FfiTextWidth {
  final String fontName;
  final double fontSize;
  final String text;
  final double width;

  const FfiTextWidth({required this.fontName, required this.fontSize, required this.text, required this.width});

  @override
  int get hashCode => fontName.hashCode ^ fontSize.hashCode ^ text.hashCode ^ width.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiTextWidth &&
          runtimeType == other.runtimeType &&
          fontName == other.fontName &&
          fontSize == other.fontSize &&
          text == other.text &&
          width == other.width;
}
