// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ContentCleaningOptions dco_decode_box_autoadd_content_cleaning_options(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  FfiBookSource dco_decode_box_autoadd_ffi_book_source(dynamic raw);

  @protected
  FfiProcessOptions dco_decode_box_autoadd_ffi_process_options(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  ChapterInfo dco_decode_chapter_info(dynamic raw);

  @protected
  ContentCleaningOptions dco_decode_content_cleaning_options(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FfiBookMetadata dco_decode_ffi_book_metadata(dynamic raw);

  @protected
  FfiBookSource dco_decode_ffi_book_source(dynamic raw);

  @protected
  FfiCacheStats dco_decode_ffi_cache_stats(dynamic raw);

  @protected
  FfiFormatInfo dco_decode_ffi_format_info(dynamic raw);

  @protected
  FfiPreloadStats dco_decode_ffi_preload_stats(dynamic raw);

  @protected
  FfiProcessOptions dco_decode_ffi_process_options(dynamic raw);

  @protected
  FfiReplaceRule dco_decode_ffi_replace_rule(dynamic raw);

  @protected
  FfiTextWidth dco_decode_ffi_text_width(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChapterInfo> dco_decode_list_chapter_info(dynamic raw);

  @protected
  List<FfiReplaceRule> dco_decode_list_ffi_replace_rule(dynamic raw);

  @protected
  List<FfiTextWidth> dco_decode_list_ffi_text_width(dynamic raw);

  @protected
  List<PageEntryInfo> dco_decode_list_page_entry_info(dynamic raw);

  @protected
  List<PageInfo> dco_decode_list_page_info(dynamic raw);

  @protected
  List<PageSegInfo> dco_decode_list_page_seg_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ContentCleaningOptions? dco_decode_opt_box_autoadd_content_cleaning_options(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  FfiProcessOptions? dco_decode_opt_box_autoadd_ffi_process_options(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  PageEntryInfo dco_decode_page_entry_info(dynamic raw);

  @protected
  PageInfo dco_decode_page_info(dynamic raw);

  @protected
  PageSegInfo dco_decode_page_seg_info(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ContentCleaningOptions sse_decode_box_autoadd_content_cleaning_options(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  FfiBookSource sse_decode_box_autoadd_ffi_book_source(SseDeserializer deserializer);

  @protected
  FfiProcessOptions sse_decode_box_autoadd_ffi_process_options(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  ChapterInfo sse_decode_chapter_info(SseDeserializer deserializer);

  @protected
  ContentCleaningOptions sse_decode_content_cleaning_options(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FfiBookMetadata sse_decode_ffi_book_metadata(SseDeserializer deserializer);

  @protected
  FfiBookSource sse_decode_ffi_book_source(SseDeserializer deserializer);

  @protected
  FfiCacheStats sse_decode_ffi_cache_stats(SseDeserializer deserializer);

  @protected
  FfiFormatInfo sse_decode_ffi_format_info(SseDeserializer deserializer);

  @protected
  FfiPreloadStats sse_decode_ffi_preload_stats(SseDeserializer deserializer);

  @protected
  FfiProcessOptions sse_decode_ffi_process_options(SseDeserializer deserializer);

  @protected
  FfiReplaceRule sse_decode_ffi_replace_rule(SseDeserializer deserializer);

  @protected
  FfiTextWidth sse_decode_ffi_text_width(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChapterInfo> sse_decode_list_chapter_info(SseDeserializer deserializer);

  @protected
  List<FfiReplaceRule> sse_decode_list_ffi_replace_rule(SseDeserializer deserializer);

  @protected
  List<FfiTextWidth> sse_decode_list_ffi_text_width(SseDeserializer deserializer);

  @protected
  List<PageEntryInfo> sse_decode_list_page_entry_info(SseDeserializer deserializer);

  @protected
  List<PageInfo> sse_decode_list_page_info(SseDeserializer deserializer);

  @protected
  List<PageSegInfo> sse_decode_list_page_seg_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ContentCleaningOptions? sse_decode_opt_box_autoadd_content_cleaning_options(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  FfiProcessOptions? sse_decode_opt_box_autoadd_ffi_process_options(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  PageEntryInfo sse_decode_page_entry_info(SseDeserializer deserializer);

  @protected
  PageInfo sse_decode_page_info(SseDeserializer deserializer);

  @protected
  PageSegInfo sse_decode_page_seg_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_content_cleaning_options(ContentCleaningOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_book_source(FfiBookSource self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_process_options(FfiProcessOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_info(ChapterInfo self, SseSerializer serializer);

  @protected
  void sse_encode_content_cleaning_options(ContentCleaningOptions self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_book_metadata(FfiBookMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_book_source(FfiBookSource self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_cache_stats(FfiCacheStats self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_format_info(FfiFormatInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_preload_stats(FfiPreloadStats self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_process_options(FfiProcessOptions self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_replace_rule(FfiReplaceRule self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_text_width(FfiTextWidth self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_info(List<ChapterInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_replace_rule(List<FfiReplaceRule> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_text_width(List<FfiTextWidth> self, SseSerializer serializer);

  @protected
  void sse_encode_list_page_entry_info(List<PageEntryInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_page_info(List<PageInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_page_seg_info(List<PageSegInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_usize_strict(Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content_cleaning_options(ContentCleaningOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ffi_process_options(FfiProcessOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_page_entry_info(PageEntryInfo self, SseSerializer serializer);

  @protected
  void sse_encode_page_info(PageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_page_seg_info(PageSegInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
