// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FFI-safe chapter info
class ChapterInfo {
  final String title;
  final BigInt startPos;
  final BigInt endPos;

  /// 章节层级：1=顶层（EPUB 嵌套目录；TXT 平铺恒为 1）
  final int level;

  /// 父章节索引（None=顶层）
  final BigInt? parentIndex;

  const ChapterInfo({
    required this.title,
    required this.startPos,
    required this.endPos,
    required this.level,
    this.parentIndex,
  });

  @override
  int get hashCode => title.hashCode ^ startPos.hashCode ^ endPos.hashCode ^ level.hashCode ^ parentIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          startPos == other.startPos &&
          endPos == other.endPos &&
          level == other.level &&
          parentIndex == other.parentIndex;
}

/// FFI-safe book source (for storage/transfer)
class FfiBookSource {
  final String bookSourceUrl;
  final String bookSourceName;
  final String bookSourceGroup;
  final bool enabled;
  final String header;
  final String cookie;
  final String ruleSearchUrl;
  final String ruleSearchBookList;
  final String ruleSearchName;
  final String ruleSearchAuthor;
  final String ruleSearchBookUrl;
  final String ruleBookInfoName;
  final String ruleBookInfoAuthor;
  final String ruleBookInfoTocUrl;
  final String ruleTocChapterList;
  final String ruleTocChapterName;
  final String ruleTocChapterUrl;
  final String ruleContentContent;
  final String ruleContentNextUrl;

  const FfiBookSource({
    required this.bookSourceUrl,
    required this.bookSourceName,
    required this.bookSourceGroup,
    required this.enabled,
    required this.header,
    required this.cookie,
    required this.ruleSearchUrl,
    required this.ruleSearchBookList,
    required this.ruleSearchName,
    required this.ruleSearchAuthor,
    required this.ruleSearchBookUrl,
    required this.ruleBookInfoName,
    required this.ruleBookInfoAuthor,
    required this.ruleBookInfoTocUrl,
    required this.ruleTocChapterList,
    required this.ruleTocChapterName,
    required this.ruleTocChapterUrl,
    required this.ruleContentContent,
    required this.ruleContentNextUrl,
  });

  @override
  int get hashCode =>
      bookSourceUrl.hashCode ^
      bookSourceName.hashCode ^
      bookSourceGroup.hashCode ^
      enabled.hashCode ^
      header.hashCode ^
      cookie.hashCode ^
      ruleSearchUrl.hashCode ^
      ruleSearchBookList.hashCode ^
      ruleSearchName.hashCode ^
      ruleSearchAuthor.hashCode ^
      ruleSearchBookUrl.hashCode ^
      ruleBookInfoName.hashCode ^
      ruleBookInfoAuthor.hashCode ^
      ruleBookInfoTocUrl.hashCode ^
      ruleTocChapterList.hashCode ^
      ruleTocChapterName.hashCode ^
      ruleTocChapterUrl.hashCode ^
      ruleContentContent.hashCode ^
      ruleContentNextUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiBookSource &&
          runtimeType == other.runtimeType &&
          bookSourceUrl == other.bookSourceUrl &&
          bookSourceName == other.bookSourceName &&
          bookSourceGroup == other.bookSourceGroup &&
          enabled == other.enabled &&
          header == other.header &&
          cookie == other.cookie &&
          ruleSearchUrl == other.ruleSearchUrl &&
          ruleSearchBookList == other.ruleSearchBookList &&
          ruleSearchName == other.ruleSearchName &&
          ruleSearchAuthor == other.ruleSearchAuthor &&
          ruleSearchBookUrl == other.ruleSearchBookUrl &&
          ruleBookInfoName == other.ruleBookInfoName &&
          ruleBookInfoAuthor == other.ruleBookInfoAuthor &&
          ruleBookInfoTocUrl == other.ruleBookInfoTocUrl &&
          ruleTocChapterList == other.ruleTocChapterList &&
          ruleTocChapterName == other.ruleTocChapterName &&
          ruleTocChapterUrl == other.ruleTocChapterUrl &&
          ruleContentContent == other.ruleContentContent &&
          ruleContentNextUrl == other.ruleContentNextUrl;
}

/// 页面内容项：文本行或图片
///
/// 判别方式：`resource_href` 为 None 即文本项，Some 即图片项。
/// 有意不用枚举——FRB 对枚举变体强制要求 freezed 依赖，
/// 与项目「手写模型、克制依赖」约定冲突。
class PageEntryInfo {
  /// 文本行内容（None=图片项）
  final String? text;

  /// 图片资源 ZIP 路径（None=文本项）
  final String? resourceHref;
  final double x;
  final double y;
  final double width;
  final double height;

  /// 行级默认色（#rrggbb；None=主题默认色，仅文本项携带）
  final String? color;

  /// 行级字号倍率（None=1.0，仅文本项携带）
  final double? fontScale;

  /// 行内富文本分段（span 等，区间为行内字符偏移；空=整行统一）
  final List<PageSegInfo> segments;

  /// P2 两端对齐：行内字符间隙（px；0=左对齐/豁免行，绘制端转 letterSpacing）
  final double letterGap;

  /// 章节首行标记（TXT 强制分页用；绘制端按粗体开关渲染标题加粗）
  final bool isChapterStart;

  /// 表格单元格线框矩形（x/y/width/height 即几何；绘制端描边）
  final bool isTableFrame;

  /// 本章说/注释行标记（小号灰字渲染；开关隐藏时 char_index 照常累计）
  final bool isComment;

  /// A31: 本行章内字符区间 [start, end)（锚点口径；表格行 0/0=未知不高亮）
  final BigInt startCharIndex;
  final BigInt endCharIndex;

  const PageEntryInfo({
    this.text,
    this.resourceHref,
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    this.color,
    this.fontScale,
    required this.segments,
    required this.letterGap,
    required this.isChapterStart,
    required this.isTableFrame,
    required this.isComment,
    required this.startCharIndex,
    required this.endCharIndex,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      resourceHref.hashCode ^
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      color.hashCode ^
      fontScale.hashCode ^
      segments.hashCode ^
      letterGap.hashCode ^
      isChapterStart.hashCode ^
      isTableFrame.hashCode ^
      isComment.hashCode ^
      startCharIndex.hashCode ^
      endCharIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageEntryInfo &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          resourceHref == other.resourceHref &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          color == other.color &&
          fontScale == other.fontScale &&
          segments == other.segments &&
          letterGap == other.letterGap &&
          isChapterStart == other.isChapterStart &&
          isTableFrame == other.isTableFrame &&
          isComment == other.isComment &&
          startCharIndex == other.startCharIndex &&
          endCharIndex == other.endCharIndex;
}

/// FFI-safe page info
class PageInfo {
  final BigInt pageIndex;
  final BigInt chapterIndex;
  final List<PageEntryInfo> entries;
  final BigInt startCharIndex;
  final BigInt endCharIndex;

  /// 整页背景图 ZIP 路径（仅结构化路径的装饰页/卷首页；每页重复携带，
  /// Dart 侧按需解码一次）
  final String? backgroundHref;

  /// 背景缩放模式："cover" | "contain" | "stretch"
  /// （绘制严格按 CSS 语义：cover=铺满裁切；None=无背景）
  final String? backgroundSize;

  /// 背景位置关键字原文（"bottom center"/"left top"...），
  /// 决定 cover 裁切锚点方位；None=居中
  final String? backgroundPosition;

  const PageInfo({
    required this.pageIndex,
    required this.chapterIndex,
    required this.entries,
    required this.startCharIndex,
    required this.endCharIndex,
    this.backgroundHref,
    this.backgroundSize,
    this.backgroundPosition,
  });

  @override
  int get hashCode =>
      pageIndex.hashCode ^
      chapterIndex.hashCode ^
      entries.hashCode ^
      startCharIndex.hashCode ^
      endCharIndex.hashCode ^
      backgroundHref.hashCode ^
      backgroundSize.hashCode ^
      backgroundPosition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageInfo &&
          runtimeType == other.runtimeType &&
          pageIndex == other.pageIndex &&
          chapterIndex == other.chapterIndex &&
          entries == other.entries &&
          startCharIndex == other.startCharIndex &&
          endCharIndex == other.endCharIndex &&
          backgroundHref == other.backgroundHref &&
          backgroundSize == other.backgroundSize &&
          backgroundPosition == other.backgroundPosition;
}

/// 文本行内样式分段
class PageSegInfo {
  final BigInt start;
  final BigInt end;

  /// 段级色覆盖（None=继承行级默认色）
  final String? color;

  /// A31-v6: 段级背景色（#rrggbb；笔记高亮用；None=无背景）
  final String? backgroundColor;

  /// 段级字号倍率覆盖（None=继承行级）
  final double? fontScale;

  /// 字形样式（绘制端按用户开关决定是否应用；下划线恒应用）
  final bool bold;
  final bool italic;
  final bool underline;

  /// P2 justify 拉丁词保护段（Some(0)=该区间不加间隙；None=继承行级）
  final double? letterSpacing;

  const PageSegInfo({
    required this.start,
    required this.end,
    this.color,
    this.backgroundColor,
    this.fontScale,
    required this.bold,
    required this.italic,
    required this.underline,
    this.letterSpacing,
  });

  @override
  int get hashCode =>
      start.hashCode ^
      end.hashCode ^
      color.hashCode ^
      backgroundColor.hashCode ^
      fontScale.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      underline.hashCode ^
      letterSpacing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageSegInfo &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          color == other.color &&
          backgroundColor == other.backgroundColor &&
          fontScale == other.fontScale &&
          bold == other.bold &&
          italic == other.italic &&
          underline == other.underline &&
          letterSpacing == other.letterSpacing;
}
