// GENERATED by scripts/gen_bg_presets.py — 内置阅读背景（明/暗成对）
class BgImagePreset {
  const BgImagePreset(this.id, this.label, this.lightAsset, this.darkAsset);
  final String id;
  final String label;
  final String lightAsset;
  final String darkAsset;
  String assetFor(bool dark) => dark ? darkAsset : lightAsset;
}

const kBgImagePresets = <BgImagePreset>[
  BgImagePreset('01_棉纸', '棉纸', 'assets/backgrounds/01_棉纸_light.jpg', 'assets/backgrounds/01_棉纸_dark.jpg'),
  BgImagePreset('02_亚麻', '亚麻', 'assets/backgrounds/02_亚麻_light.jpg', 'assets/backgrounds/02_亚麻_dark.jpg'),
  BgImagePreset('03_水墨', '水墨', 'assets/backgrounds/03_水墨_light.jpg', 'assets/backgrounds/03_水墨_dark.jpg'),
  BgImagePreset('04_石纹', '石纹', 'assets/backgrounds/04_石纹_light.jpg', 'assets/backgrounds/04_石纹_dark.jpg'),
  BgImagePreset('05_古典-织锦', '古典-织锦', 'assets/backgrounds/05_古典-织锦_light.jpg', 'assets/backgrounds/05_古典-织锦_dark.jpg'),
  BgImagePreset('06_古典-青瓷', '古典-青瓷', 'assets/backgrounds/06_古典-青瓷_light.jpg', 'assets/backgrounds/06_古典-青瓷_dark.jpg'),
  BgImagePreset('07_古典-云纹', '古典-云纹', 'assets/backgrounds/07_古典-云纹_light.jpg', 'assets/backgrounds/07_古典-云纹_dark.jpg'),
  BgImagePreset('08_仙侠-灵脉', '仙侠-灵脉', 'assets/backgrounds/08_仙侠-灵脉_light.jpg', 'assets/backgrounds/08_仙侠-灵脉_dark.jpg'),
  BgImagePreset('09_仙侠-云海', '仙侠-云海', 'assets/backgrounds/09_仙侠-云海_light.jpg', 'assets/backgrounds/09_仙侠-云海_dark.jpg'),
  BgImagePreset('10_仙侠-流光', '仙侠-流光', 'assets/backgrounds/10_仙侠-流光_light.jpg', 'assets/backgrounds/10_仙侠-流光_dark.jpg'),
  BgImagePreset('11_深海-沉船', '深海-沉船', 'assets/backgrounds/11_深海-沉船_light.jpg', 'assets/backgrounds/11_深海-沉船_dark.jpg'),
  BgImagePreset('12_深海-废墟', '深海-废墟', 'assets/backgrounds/12_深海-废墟_light.jpg', 'assets/backgrounds/12_深海-废墟_dark.jpg'),
  BgImagePreset('13_深海-遗迹', '深海-遗迹', 'assets/backgrounds/13_深海-遗迹_light.jpg', 'assets/backgrounds/13_深海-遗迹_dark.jpg'),
  BgImagePreset('14_科幻-星舰', '科幻-星舰', 'assets/backgrounds/14_科幻-星舰_light.jpg', 'assets/backgrounds/14_科幻-星舰_dark.jpg'),
  BgImagePreset('15_科幻-空间站', '科幻-空间站', 'assets/backgrounds/15_科幻-空间站_light.jpg', 'assets/backgrounds/15_科幻-空间站_dark.jpg'),
  BgImagePreset('16_科幻-废土', '科幻-废土', 'assets/backgrounds/16_科幻-废土_light.jpg', 'assets/backgrounds/16_科幻-废土_dark.jpg'),
  BgImagePreset('17_模仿-红衣', '模仿-红衣', 'assets/backgrounds/17_模仿-红衣_light.jpg', 'assets/backgrounds/17_模仿-红衣_dark.jpg'),
  BgImagePreset('18_仙侠-桃花云山', '仙侠-桃花云山', 'assets/backgrounds/18_仙侠-桃花云山_light.jpg', 'assets/backgrounds/18_仙侠-桃花云山_dark.jpg'),
  BgImagePreset('19_仙侠-仙台楼阁', '仙侠-仙台楼阁', 'assets/backgrounds/19_仙侠-仙台楼阁_light.jpg', 'assets/backgrounds/19_仙侠-仙台楼阁_dark.jpg'),
  BgImagePreset('20_仙侠-高山流水', '仙侠-高山流水', 'assets/backgrounds/20_仙侠-高山流水_light.jpg', 'assets/backgrounds/20_仙侠-高山流水_dark.jpg'),
  BgImagePreset('21_仙侠-云海仙桥', '仙侠-云海仙桥', 'assets/backgrounds/21_仙侠-云海仙桥_light.jpg', 'assets/backgrounds/21_仙侠-云海仙桥_dark.jpg'),
  BgImagePreset('22_护眼-竹径', '护眼-竹径', 'assets/backgrounds/22_护眼-竹径_light.jpg', 'assets/backgrounds/22_护眼-竹径_dark.jpg'),
  BgImagePreset('23_护眼-竹溪', '护眼-竹溪', 'assets/backgrounds/23_护眼-竹溪_light.jpg', 'assets/backgrounds/23_护眼-竹溪_dark.jpg'),
  BgImagePreset('24_护眼-雨竹亭', '护眼-雨竹亭', 'assets/backgrounds/24_护眼-雨竹亭_light.jpg', 'assets/backgrounds/24_护眼-雨竹亭_dark.jpg'),
];
