import os
import re

dst = r"D:\android\example\legado_flutter\assets\backgrounds"
files = sorted(os.listdir(dst))
sets = {}
for f in files:
    m = re.match(r"(\d+)_(.+)_((?:light)|(?:dark))\.jpg$", f)
    if not m:
        continue
    num, name, mode = m.groups()
    sets.setdefault((num, name), {})[mode] = f

out = []
out.append("// GENERATED by scripts/gen_bg_presets.py — 内置阅读背景（明/暗成对）")
out.append("class BgImagePreset {")
out.append("  const BgImagePreset(this.id, this.label, this.lightAsset, this.darkAsset);")
out.append("  final String id;")
out.append("  final String label;")
out.append("  final String lightAsset;")
out.append("  final String darkAsset;")
out.append("  String assetFor(bool dark) => dark ? darkAsset : lightAsset;")
out.append("}")
out.append("")
out.append("const kBgImagePresets = <BgImagePreset>[")
for (num, name), v in sorted(sets.items()):
    light = v.get("light", "")
    dark = v.get("dark", "")
    out.append(
        f"  BgImagePreset('{num}_{name}', '{name}', "
        f"'assets/backgrounds/{light}', 'assets/backgrounds/{dark}'),"
    )
out.append("];")
out.append("")

path = os.path.join(
    r"D:\android\example\legado_flutter\lib\features\reader\presentation\services",
    "bg_image_presets.dart",
)
with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(out))
print("wrote", path, "count", len(sets))
